# Generated by Django 5.2.5 on 2025-09-11 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('light', models.FloatField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'datasensor',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='historyaction',
            name='timetamp',
        ),
        migrations.RemoveField(
            model_name='historyaction',
            name='user',
        ),
        migrations.AddField(
            model_name='historyaction',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historyaction',
            name='action',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='historyaction',
            name='device',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='historyaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='historyaction',
            table='historyaction',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
